#!/bin/sh

echo "Running pycodestyle checks"

if ! which pycodestyle > /dev/null; then
    echo "Please install the pycodestyle tool"
    exit 0
fi

pycodestyle --max-line-length=150 --max-doc-length=150 --ignore=E402,E201,E202,E128,E241,W504
